---
title: "Voluntary Ecosystem Review Barcelona '2022'"
author: "Syd Kotar"
date: "13 April 2022"
output:
  html_document: 
    toc: true
    toc_depth: 4
    number_sections: true
    toc_float: true
---

Load Libraries
```{r Data Import and Packages, echo = FALSE, results = 'hide', error = FALSE, warning = FALSE, message = FALSE}
library(corrplot)
library(tidyverse)
library(readr)
library(ggpubr)
library(data.table)
library(readxl)
library(knitr)

```

Load Data
```{r Packages, echo = FALSE, results = 'hide', error = FALSE, warning = FALSE, message = FALSE}
company_raw <- read_excel("Company.xls")
#View(Company)
startup_raw <- read_excel("Startup.xlsx")
#View(Startup)
```

# Data Tidying

Results and data ... 

```{r Data Tidying, echo = FALSE, results = 'hide', error = FALSE, warning = FALSE, message = FALSE}

#Company Indicator
company_sdg <- company_raw %>% #group by only SDGs
  group_by(SDG.1, SDG.2, SDG.3, SDG.4, SDG.5, SDG.6, SDG.7,
           SDG.8,SDG.9,SDG.10,SDG.11,SDG.12,SDG.13,SDG.14,
           SDG.15,SDG.16,SDG.17) %>% 
  summarise() %>% 
  ungroup()

company_sdg <- company_sdg %>% #Rename columns in preparation for figure
  setnames("SDG.1", "SDG 1") %>% 
  setnames("SDG.2", "SDG 2") %>% 
  setnames("SDG.3", "SDG 3") %>% 
  setnames("SDG.4", "SDG 4") %>% 
  setnames("SDG.5", "SDG 5") %>% 
  setnames("SDG.6", "SDG 6") %>% 
  setnames("SDG.7", "SDG 7") %>% 
  setnames("SDG.8", "SDG 8") %>% 
  setnames("SDG.9", "SDG 9") %>% 
  setnames("SDG.10", "SDG 10") %>% 
  setnames("SDG.11", "SDG 11") %>% 
  setnames("SDG.12", "SDG 12") %>% 
  setnames("SDG.13", "SDG 13") %>% 
  setnames("SDG.14", "SDG 14") %>% 
  setnames("SDG.15", "SDG 15") %>% 
  setnames("SDG.16", "SDG 16") %>% 
  setnames("SDG.17", "SDG 17")

#Factor SDGs
# company <- company %>% 
#   mutate(SDG.1 = factor(SDG.1, levels = c("1", "0"))) %>% 
#   mutate(SDG.2 = factor(SDG.2, levels = c("1", "0"))) %>% 
#   mutate(SDG.3 = factor(SDG.3, levels = c("1", "0"))) %>% 
#   mutate(SDG.4 = factor(SDG.4, levels = c("1", "0"))) %>% 
#   mutate(SDG.5 = factor(SDG.5, levels = c("1", "0"))) %>% 
#   mutate(SDG.6 = factor(SDG.6, levels = c("1", "0"))) %>% 
#   mutate(SDG.7 = factor(SDG.7, levels = c("1", "0"))) %>% 
#   mutate(SDG.8 = factor(SDG.8, levels = c("1", "0"))) %>% 
#   mutate(SDG.9 = factor(SDG.9, levels = c("1", "0"))) %>% 
#   mutate(SDG.10 = factor(SDG.10, levels = c("1", "0"))) %>% 
#   mutate(SDG.11 = factor(SDG.11, levels = c("1", "0"))) %>% 
#   mutate(SDG.12 = factor(SDG.12, levels = c("1", "0"))) %>% 
#   mutate(SDG.13 = factor(SDG.13, levels = c("1", "0"))) %>% 
#   mutate(SDG.14 = factor(SDG.14, levels = c("1", "0"))) %>% 
#   mutate(SDG.15 = factor(SDG.15, levels = c("1", "0"))) %>% 
#   mutate(SDG.16 = factor(SDG.16, levels = c("1", "0"))) %>% 
#   mutate(SDG.17 = factor(SDG.17, levels = c("1", "0")))

#Startup Indicator
startup_sdg <- startup_raw %>% #group by sdgs
  group_by(SDG1, SDG2, SDG3, SDG4, SDG5, SDG6, SDG7,
           SDG8,SDG9,SDG10,SDG11,SDG12,SDG13,SDG14,
           SDG15,SDG16,SDG17) %>% 
  summarise() %>% 
  ungroup()

startup_sdg <- startup_sdg %>% 
  setnames("SDG1", "SDG 1") %>% 
  setnames("SDG2", "SDG 2") %>% 
  setnames("SDG3", "SDG 3") %>% 
  setnames("SDG4", "SDG 4") %>% 
  setnames("SDG5", "SDG 5") %>% 
  setnames("SDG6", "SDG 6") %>% 
  setnames("SDG7", "SDG 7") %>% 
  setnames("SDG8", "SDG 8") %>% 
  setnames("SDG9", "SDG 9") %>% 
  setnames("SDG10", "SDG 10") %>% 
  setnames("SDG11", "SDG 11") %>% 
  setnames("SDG12", "SDG 12") %>% 
  setnames("SDG13", "SDG 13") %>% 
  setnames("SDG14", "SDG 14") %>% 
  setnames("SDG15", "SDG 15") %>% 
  setnames("SDG16", "SDG 16") %>% 
  setnames("SDG17", "SDG 17")



```

# Company Indicator
This is the data analysis for the company indicator. 

## Company P-Correlation Matrix
```{r Company P-Correlation Matrix, echo = FALSE, results = 'hide', error = FALSE, warning = FALSE, message = FALSE}
A = cor(company_sdg)
corrplot(A, method = 'number', number.cex=0.5, tl.cex=1)
```

## Company Circle Matrix
```{r Company Circle Matrix, echo = FALSE, results = 'hide', error = FALSE, warning = FALSE, message = FALSE}

corrplot(A,
         number.cex=0.75,
         tl.cex=1)
```
# Startup Indicator

## Startup P-Correlation Matrix
```{r Startup P-Correlation Matrix, echo = FALSE, results = 'hide', error = FALSE, warning = FALSE, message = FALSE}
B = cor(startup_sdg, use="pairwise.complete.obs")
corrplot(B, method = 'number', na.label="NA", number.cex=0.5, tl.cex=1)
```

## Startup Circle Matrix
```{r Startup Circle Matrix, echo = FALSE, results = 'hide', error = FALSE, warning = FALSE, message = FALSE}

corrplot(B,
         number.cex=0.75,
         tl.cex=1,
         na.label="NA")
```



